# Generated by Django 5.1.2 on 2025-03-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('last_watered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latin', models.CharField(max_length=255)),
                ('family', models.CharField(max_length=255)),
                ('common', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('climate', models.CharField(max_length=255)),
                ('tempmax', models.JSONField(blank=True, default=dict)),
                ('tempmin', models.JSONField(blank=True, default=dict)),
                ('ideallight', models.CharField(max_length=255)),
                ('toleratedlight', models.CharField(max_length=255)),
                ('watering', models.CharField(max_length=255)),
                ('insects', models.JSONField(blank=True, default=list)),
                ('diseases', models.CharField(max_length=255)),
                ('use', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
