# Generated by Django 5.1.2 on 2025-03-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planttype',
            old_name='ideallight',
            new_name='ideal_light',
        ),
        migrations.RenameField(
            model_name='planttype',
            old_name='latin',
            new_name='latin_name',
        ),
        migrations.RenameField(
            model_name='planttype',
            old_name='toleratedlight',
            new_name='tolerated_light',
        ),
        migrations.RemoveField(
            model_name='planttype',
            name='common',
        ),
        migrations.RemoveField(
            model_name='planttype',
            name='tempmax',
        ),
        migrations.RemoveField(
            model_name='planttype',
            name='tempmin',
        ),
        migrations.AddField(
            model_name='planttype',
            name='common_name',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='planttype',
            name='temp_max',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='planttype',
            name='temp_min',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='planttype',
            name='insects',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='planttype',
            name='use',
            field=models.JSONField(default=list),
        ),
    ]
