# Generated by Django 5.1.2 on 2025-04-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
